In [2]:
import pandas as pd

In [10]:
s = pd.Series([10, 20, 30, 40])
print(s)

s2 = pd.Series([85, 90, 95], index = ["국어", "영어", "수학"])
print(s2)
print(s2.get("국어"))

0    10
1    20
2    30
3    40
dtype: int64
국어    85
영어    90
수학    95
dtype: int64
85

In [12]:
data = {
    "이름": ["철수", "영희", "민수"],
    "나이": [25, 22, 28],
    "도시": ["서울", "부산", "대구"]
}
df = pd.DataFrame(data)
print(df)

values = [
    [1, 2, 3],
    [4, 5, 6]
]
df2 = pd.DataFrame(values, columns = ["A", "B", "C"])
print(df2)

   이름  나이  도시
0  철수  25  서울
1  영희  22  부산
2  민수  28  대구
   A  B  C
0  1  2  3
1  4  5  6

In [17]:
x = [10, 20, 30, 40, 50]
y = pd.Series(x)
print(y)

y = pd.Series(x, index = ["홍길동", "이길동", "삼길동", "사길동", "오길동"])
print(y)

d = {
    "apple": 1000,
    "banana": 3000,
    "orange": 1000
}
y = pd.Series(d)
print(y)
print(y.index)
print(y.values)

0    10
1    20
2    30
3    40
4    50
dtype: int64
홍길동    10
이길동    20
삼길동    30
사길동    40
오길동    50
dtype: int64
apple     1000
banana    3000
orange    1000
dtype: int64
Index(['apple', 'banana', 'orange'], dtype='str')
[1000 3000 1000]

In [18]:
x = [10, 20, 30, 40, 50]
s = pd.Series(x)
print(s)
a = s.sum()
print("합", a)
a = s.max()
print("최대값", a)
a = s.min()
print("최소값", a)
a = s.mean()
print("평균값", a)
a = s.median()
print("중위값", a)
a = s.std()
print("표준편차", a)

0    10
1    20
2    30
3    40
4    50
dtype: int64
합 150
최대값 50
최소값 10
평균값 30.0
중위값 30.0
표준편차 15.811388300841896

In [30]:
x = pd.Series([10, 20, 30, 40, 40, 40, 50, 10, 100])
y = x.value_counts().sort_values()[::-1]
print(y)
y = x[x >= 40]
print(y)
y = x[(x >= 30) & (x <= 50)]
print(y)
y = x.sort_values()
print(y)
y = x.sort_values(ascending = False)
print(y)

40     3
10     2
50     1
100    1
20     1
30     1
Name: count, dtype: int64
3     40
4     40
5     40
6     50
8    100
dtype: int64
2    30
3    40
4    40
5    40
6    50
dtype: int64
0     10
7     10
1     20
2     30
3     40
4     40
5     40
6     50
8    100
dtype: int64
8    100
6     50
5     40
4     40
3     40
2     30
1     20
0     10
7     10
dtype: int64

In [37]:
x = pd.Series([10, 20, 30, 40, 50, 100], index = [1, 2, 3, 4, 5, 6])
print(x)
print(x.loc[1])
print(x.iloc[1])

x = [10, 20, 30, 40, 50]
y = pd.Series(x, index = ["홍길동", "이길동", "삼길동", "사길동", "오길동"])
print(y)
print(y.iloc[1:3])
print(y.loc["홍길동":"사길동"])

1     10
2     20
3     30
4     40
5     50
6    100
dtype: int64
10
20
홍길동    10
이길동    20
삼길동    30
사길동    40
오길동    50
dtype: int64
이길동    20
삼길동    30
dtype: int64
홍길동    10
이길동    20
삼길동    30
사길동    40
dtype: int64

In [28]:
data = {
    "학번": [1, 2, 3, 4, 5],
    "이름": ["이", "김", "나", "박", "성"],
    "나이": [10, 20, 30, 33, 22],
    "점수": [44, 55, 66, 100, 100]
}
df = pd.DataFrame(data)
df.to_csv("students.csv", index=False)
df

   학번 이름  나이   점수
0   1  이  10   44
1   2  김  20   55
2   3  나  30   66
3   4  박  33  100
4   5  성  22  100

In [29]:
df1 = pd.read_csv("students.csv")
df1

   학번 이름  나이   점수
0   1  이  10   44
1   2  김  20   55
2   3  나  30   66
3   4  박  33  100
4   5  성  22  100

In [31]:
df.to_excel("students.xlsx", index=False)

In [33]:
df1 = pd.read_excel("students.xlsx")
df1

   학번 이름  나이   점수
0   1  이  10   44
1   2  김  20   55
2   3  나  30   66
3   4  박  33  100
4   5  성  22  100

In [42]:
data = {
    "이름": ["철수", "영희", "민수", "지은", "우진"],
    "나이": [25, 22, 28, 31, 19],
    "점수": [85, 90, 78, 92, 60]
}
df = pd.DataFrame(data)
print(df)

   이름  나이  점수
0  철수  25  85
1  영희  22  90
2  민수  28  78
3  지은  31  92
4  우진  19  60

In [ ]:
print(df["이름"])
print(df[["이름"]])
print(df[["이름", "점수"]])

0    철수
1    영희
2    민수
3    지은
4    우진
Name: 이름, dtype: str
<class 'pandas.Series'>
   이름
0  철수
1  영희
2  민수
3  지은
4  우진
<class 'pandas.DataFrame'>
   이름  점수
0  철수  85
1  영희  90
2  민수  78
3  지은  92
4  우진  60
<class 'pandas.DataFrame'>

In [ ]:
print(df.loc[0, "이름"])
print(df.loc[0:2, "이름"])
print(df.iloc[0:2, 0:2])
print(df.loc[2])
print(df.iloc[-1])

철수
<class 'str'>
0    철수
1    영희
2    민수
Name: 이름, dtype: str
<class 'pandas.Series'>
   이름  나이
0  철수  25
1  영희  22
<class 'pandas.DataFrame'>
이름    민수
나이    28
점수    78
Name: 2, dtype: object
<class 'pandas.Series'>
이름    우진
나이    19
점수    60
Name: 4, dtype: object
<class 'pandas.Series'>

In [61]:
print(df["나이"] >= 25)
print(df[df["나이"] >= 25])
print(df[(df["나이"] >= 25) & (df["점수"] >= 80)])
print(df.loc[df["점수"] >= 80, ["이름", "나이"]])

0     True
1    False
2     True
3     True
4    False
Name: 나이, dtype: bool
   이름  나이  점수
0  철수  25  85
2  민수  28  78
3  지은  31  92
   이름  나이  점수
0  철수  25  85
3  지은  31  92
   이름  나이
0  철수  25
1  영희  22
3  지은  31

In [64]:
print(df[[True, False, True, True,True]])
print(df["이름"].isin(["철수", "영희"]))
print(df[df["이름"].isin(["철수", "영희"])])
print(df["나이"].between(20, 28))
print(df[df["나이"].between(20, 28)])

   이름  나이  점수
0  철수  25  85
2  민수  28  78
3  지은  31  92
4  우진  19  60
0     True
1     True
2    False
3    False
4    False
Name: 이름, dtype: bool
   이름  나이  점수
0  철수  25  85
1  영희  22  90
0     True
1     True
2     True
3    False
4    False
Name: 나이, dtype: bool
   이름  나이  점수
0  철수  25  85
1  영희  22  90
2  민수  28  78

In [68]:
data = {
    "이름": ["철수", "영희", "민수", "지은", "우진"],
    "나이": [25, 22, 28, 31, 19],
    "점수": [85, 90, 78, 92, 60]
}
df = pd.DataFrame(data)
df1 = df.set_index("이름")
df

   이름  나이  점수
0  철수  25  85
1  영희  22  90
2  민수  28  78
3  지은  31  92
4  우진  19  60

In [67]:
df.set_index("이름", inplace = True)
df

    나이  점수
이름
철수  25  85
영희  22  90
민수  28  78
지은  31  92
우진  19  60