In [7]:
import pandas as pd
import numpy as np

In [3]:
fruit_data = {
    "과일": ["사과", "바나나", "포도", "딸기", "수박"],
    "가격": [3000, 1500, 5000, 4000, 15000],
    "재고": [10, 25, 7, 15, 3]
}

In [15]:
"""
1. 과일이름과 재고를 조회해 보세요.
"""

df = pd.DataFrame(fruit_data)
df[["과일", "재고"]].set_index("과일")

     재고
과일
사과   10
바나나  25
포도    7
딸기   15
수박    3

In [15]:
"""
2. 가격이 4000원 이상인 과일만 조회해 보세요.
"""

df.loc[df["가격"] >= 4000, ["과일", "가격"]].set_index("과일")

       가격
과일
포도   5000
딸기   4000
수박  15000

In [16]:
"""
3. 가격이 4000원 이상이면서 재고가 10개 이하인 과일을 조회해 보세요.
"""

df.loc[(df["가격"] >= 4000) & (df["재고"] <= 10), ["과일", "가격", "재고"]].set_index("과일")

       가격  재고
과일
포도   5000   7
수박  15000   3

In [17]:
"""
4. loc을 이용해서 0번 인덱스의 "과일" 값을 조회해 보세요.
"""

df.loc[0, "과일"]

'사과'

In [18]:
"""
5. iloc을 이용해서 0~2번 행(포함), 0~1번 열(포함)을 조회해 보세요.
"""

df.iloc[0:3, 0:2]

    과일    가격
0   사과  3000
1  바나나  1500
2   포도  5000

In [19]:
"""
6. "과일" 컬럼을 인덱스로 설정해 보세요. (원본은 바뀌지 않도록)
"""

df.set_index("과일")

        가격  재고
과일
사과    3000  10
바나나   1500  25
포도    5000   7
딸기    4000  15
수박   15000   3

In [20]:
"""
7. isin()을 이용해서 "바나나"와 "수박"에 해당하는 행만 조회해 보세요.
"""

df[df["과일"].isin(["바나나", "수박"])]

    과일     가격  재고
1  바나나   1500  25
4   수박  15000   3

In [21]:
"""
8. between()을 이용해서 가격이 3000원 이상 5000원 이하인 과일을 조회해 보세요.
"""

df[df["가격"].between(3000, 5000)]

   과일    가격  재고
0  사과  3000  10
2  포도  5000   7
3  딸기  4000  15

In [22]:
"""
9. describe()를 이용해서 가격과 재고의 통계 요약 정보를 확인해 보세요.
"""

df[["가격", "재고"]].describe()

                 가격         재고
count      5.000000   5.000000
mean    5700.000000  12.000000
std     5357.238094   8.485281
min     1500.000000   3.000000
25%     3000.000000   7.000000
50%     4000.000000  10.000000
75%     5000.000000  15.000000
max    15000.000000  25.000000