In [1]:
import pandas as pd
import numpy as np

In [35]:
fruit_data = {
    "과일": ["사과", "바나나", "포도", "딸기", "수박", "참외", "사과", "바나나"],
    "분류": ["국산", "수입", "국산", "국산", "국산", "국산", "국산", "수입"],
    "가격": [3000, 1500, 5000, 4000, 15000, np.nan, 3500, 1800], # 결측치 포함
    "재고": [10, 25, 7, 15, 3, 12, 8, 20]
}
df = pd.DataFrame(fruit_data)

Q1. [결측치 처리] "가격" 컬럼에 NaN(결측치) 데이터가 있습니다. 가격이 비어있는 행을 찾아서 전체 가격의 평균값으로 채워 넣어보세요. (힌트: fillna, mean 사용)

In [33]:

mean_price = int((df["가격"].mean().round()))
df.fillna({"가격": mean_price}, inplace = True)
df["가격"] = df["가격"].astype("int64")
df

   과일  분류     가격  재고   총재고액
4  수박  국산  15000   3  45000
2  포도  국산   5000   7  35000
5  참외  국산   4829  12  57948
3  딸기  국산   4000  15  60000
6  사과  국산   3500   8  28000
0  사과  국산   3000  10  30000

Q2. [정렬 및 다중 조건] "분류"가 "국산"인 과일들만 골라낸 뒤, "가격"은 비싼 순서대로(내림차순), 가격이 같다면 "재고"가 많은 순서대로(내림차순) 정렬해 보세요. (힌트: sort_values에 리스트 사용)

In [34]:
df[df["분류"] == "국산"].sort_values(["가격", "재고"], ascending=False)

   과일  분류     가격  재고   총재고액
4  수박  국산  15000   3  45000
2  포도  국산   5000   7  35000
5  참외  국산   4829  12  57948
3  딸기  국산   4000  15  60000
6  사과  국산   3500   8  28000
0  사과  국산   3000  10  30000

Q3. [파생 변수 생성] "가격"과 "재고"를 곱해서 "총재고액"이라는 새로운 컬럼을 만들어 보세요.

In [31]:
df["총재고액"] = df["가격"] * df["재고"]
df

   과일  분류     가격  재고   총재고액
4  수박  국산  15000   3  45000
2  포도  국산   5000   7  35000
5  참외  국산   4829  12  57948
3  딸기  국산   4000  15  60000
6  사과  국산   3500   8  28000
0  사과  국산   3000  10  30000

Q4. [그룹화 및 통계] "분류"(국산/수입)별로 "가격"의 평균과 "재고"의 총합합계를 각각 구해 보세요. (힌트: groupby와 agg 사용)

In [37]:
df.groupby("분류").agg(가격평균=("가격", "mean"), 재고=("재고", "sum"))

      가격평균  재고
분류
국산  6100.0  55
수입  1650.0  45

In [16]:
df.groupby("분류")["재고"].sum()

분류
국산    55
수입    45
Name: 재고, dtype: int64

Q5. [조건 기반 값 변경] np.where 또는 판다스의 .loc을 활용하여, 가격이 5000원 이상이면 "프리미엄", 5000원 미만이면 "일반"이라는 값을 가지는 "등급" 컬럼을 새로 만들어 보세요.

In [17]:
df["등급"] = df["가격"].apply(lambda price: "프리미엄" if price >= 5000 else "일반")
df

    과일  분류     가격  재고   총재고액    등급
0   사과  국산   3000  10  30000    일반
1  바나나  수입   1500  25  37500    일반
2   포도  국산   5000   7  35000  프리미엄
3   딸기  국산   4000  15  60000    일반
4   수박  국산  15000   3  45000  프리미엄
5   참외  국산   4829  12  57948    일반
6   사과  국산   3500   8  28000    일반
7  바나나  수입   1800  20  36000    일반

Q6. [텍스트 필터링] "과일" 이름에 "바"자가 포함된 과일의 행들만 필터링해 보세요. (힌트: .str.contains() 사용)

In [18]:
df[df["과일"].str.contains("바")]

    과일  분류    가격  재고   총재고액  등급
1  바나나  수입  1500  25  37500  일반
7  바나나  수입  1800  20  36000  일반

Q7. [인덱스 초기화] Q2번이나 Q6번처럼 필터링을 하고 나면 인덱스 번호가 듬성듬성해집니다(1, 7 등). 이 인덱스를 다시 0부터 순서대로 이쁘게 정렬해 보세요. (기존 인덱스는 삭제) (힌트: reset_index 사용)

In [26]:
df.reset_index()

   index  과일  분류     가격  재고   총재고액    등급
0      4  수박  국산  15000   3  45000  프리미엄
1      2  포도  국산   5000   7  35000  프리미엄
2      5  참외  국산   4829  12  57948    일반
3      3  딸기  국산   4000  15  60000    일반
4      6  사과  국산   3500   8  28000    일반
5      0  사과  국산   3000  10  30000    일반