In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "학번": [100, 101, 102, 103, 104, 105],
    "이름": ["김나라", "이철수", "이영희", "김세미", "홍길동", "최순이"],
    "나이": [20, 30, 21, 22, 34, 24],
    "점수": [50, 60, 70, 100, 80, 20]
}
df = pd.DataFrame(data)
df

    학번   이름  나이   점수
0  100  김나라  20   50
1  101  이철수  30   60
2  102  이영희  21   70
3  103  김세미  22  100
4  104  홍길동  34   80
5  105  최순이  24   20

In [36]:
df.describe()

               학번         나이          점수
count    6.000000   6.000000    6.000000
mean   102.500000  25.166667   63.333333
std      1.870829   5.600595   27.325202
min    100.000000  20.000000   20.000000
25%    101.250000  21.250000   52.500000
50%    102.500000  23.000000   65.000000
75%    103.750000  28.500000   77.500000
max    105.000000  34.000000  100.000000

In [50]:
data = {
    "이름": ["철수", "영희", np.nan, "지은"],
    "나이": [25, np.nan, np.nan, 31],
    "점수": [85, 90, np.nan, 92]
}
df = pd.DataFrame(data)
df

    이름    나이    점수
0   철수  25.0  85.0
1   영희   NaN  90.0
2  NaN   NaN   NaN
3   지은  31.0  92.0

In [41]:
df.isnull()

      이름     나이     점수
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [42]:
df.isnull().sum()

이름    0
나이    1
점수    1
dtype: int64

In [44]:
df_dropped = df.dropna()
df_dropped

   이름    나이    점수
0  철수  25.0  85.0
3  지은  31.0  92.0

In [45]:
df_dropped2 = df.dropna(subset = ["나이"])
df_dropped2

   이름    나이    점수
0  철수  25.0  85.0
2  민수  28.0   NaN
3  지은  31.0  92.0

In [52]:
df_dropped3 = df.dropna(how = "any")
df_dropped3

   이름    나이    점수
0  철수  25.0  85.0
3  지은  31.0  92.0

In [54]:
df_filled = df.fillna(0)
df_filled

   이름    나이    점수
0  철수  25.0  85.0
1  영희   0.0  90.0
2   0   0.0   0.0
3  지은  31.0  92.0

In [55]:
df_filled2 = df.fillna({
    "나이": 0,
    "점수": df["점수"].mean()
})
df_filled2

    이름    나이    점수
0   철수  25.0  85.0
1   영희   0.0  90.0
2  NaN   0.0  89.0
3   지은  31.0  92.0

In [56]:
df["나이"] = df["나이"].fillna(df["나이"].mean())
df

    이름    나이    점수
0   철수  25.0  85.0
1   영희  28.0  90.0
2  NaN  28.0   NaN
3   지은  31.0  92.0

In [57]:
data = {
    "이름": ["철수", "영희", "민수"],
    "국어": [80, 90, 70],
    "영어": [85, 95, 75]
}
df = pd.DataFrame(data)

In [58]:
df["총점"] = df["국어"] + df["영어"]
df

   이름  국어  영어   총점
0  철수  80  85  165
1  영희  90  95  185
2  민수  70  75  145

In [59]:
df["평균"] = df["총점"] / 2
df

   이름  국어  영어   총점    평균
0  철수  80  85  165  82.5
1  영희  90  95  185  92.5
2  민수  70  75  145  72.5

In [61]:
df["결과"] = df["평균"].apply(lambda x: "합격" if x >= 80 else "불합격")
df

   이름  국어  영어   총점    평균   결과
0  철수  80  85  165  82.5   합격
1  영희  90  95  185  92.5   합격
2  민수  70  75  145  72.5  불합격

In [63]:
df_dropped = df.drop(columns = ["총점"])
df_dropped

   이름  국어  영어    평균   결과
0  철수  80  85  82.5   합격
1  영희  90  95  92.5   합격
2  민수  70  75  72.5  불합격

In [65]:
df_dropped2 = df.drop(columns = ["총점", "평균"])
df_dropped2

   이름  국어  영어   결과
0  철수  80  85   합격
1  영희  90  95   합격
2  민수  70  75  불합격

In [66]:
df.drop(columns = ["결과"], inplace = True)
df

   이름  국어  영어   총점    평균
0  철수  80  85  165  82.5
1  영희  90  95  185  92.5
2  민수  70  75  145  72.5

In [69]:
df_dropped3 = df.drop(index = [0])
df_dropped3

   이름  국어  영어   총점    평균
1  영희  90  95  185  92.5
2  민수  70  75  145  72.5

In [73]:
df_renamed = df.rename(columns = {
    "국어": "한국어",
    "영어": "English"
})
df_renamed

   이름  한국어  English   총점    평균
0  철수   80       85  165  82.5
1  영희   90       95  185  92.5
2  민수   70       75  145  72.5

In [3]:
data = {
    "부서": ["영업", "영업", "개발", "개발", "개발", "인사"],
    "이름": ["철수", "영희", "민수", "지은", "우진", "하늘"],
    "연봉": [3500, 4000, 5000, 4800, 5200, 3800],
    "나이": [28, 32, 27, 30, 35, 26]
}
df = pd.DataFrame(data)
df

   부서  이름    연봉  나이
0  영업  철수  3500  28
1  영업  영희  4000  32
2  개발  민수  5000  27
3  개발  지은  4800  30
4  개발  우진  5200  35
5  인사  하늘  3800  26

In [4]:
df.groupby("부서")["연봉"].mean()

부서
개발    5000.0
영업    3750.0
인사    3800.0
Name: 연봉, dtype: float64

In [5]:
df.groupby("부서")["연봉"].sum()

부서
개발    15000
영업     7500
인사     3800
Name: 연봉, dtype: int64

In [6]:
df.groupby("부서")["이름"].count()

부서
개발    3
영업    2
인사    1
Name: 이름, dtype: int64

In [7]:
df.groupby("부서")["연봉"].max()

부서
개발    5200
영업    4000
인사    3800
Name: 연봉, dtype: int64

In [8]:
df.groupby("부서")["연봉"].min()

부서
개발    4800
영업    3500
인사    3800
Name: 연봉, dtype: int64

In [10]:
df.groupby("부서")["연봉"].agg(["mean", "sum", "count", "max", "min"])

      mean    sum  count   max   min
부서
개발  5000.0  15000      3  5200  4800
영업  3750.0   7500      2  4000  3500
인사  3800.0   3800      1  3800  3800

In [11]:
df.groupby("부서").agg({
    "연봉": "mean",
    "나이": "max"
})

        연봉  나이
부서
개발  5000.0  35
영업  3750.0  32
인사  3800.0  26

In [14]:
df.groupby("부서")["연봉"].mean().sort_values(ascending=False)

부서
개발    5000.0
인사    3800.0
영업    3750.0
Name: 연봉, dtype: float64

In [15]:
df.groupby("부서")["연봉"].mean().reset_index()

   부서      연봉
0  개발  5000.0
1  영업  3750.0
2  인사  3800.0

In [16]:
data2 = {
    "부서": ["영업", "영업", "개발", "개발"],
    "직급": ["사원", "대리", "사원", "대리"],
    "연봉": [3200, 3900, 4200, 4900]
}
df2 = pd.DataFrame(data2)
df2.groupby(["부서", "직급"])["연봉"].mean()

부서  직급
개발  대리    4900.0
    사원    4200.0
영업  대리    3900.0
    사원    3200.0
Name: 연봉, dtype: float64

In [17]:
df1 = pd.DataFrame({
    "이름": ["철수", "영희"],
    "점수": [85, 90]
})
df2 = pd.DataFrame({
    "이름": ["민수", "지은"],
    "점수": [78, 92]
})
result = pd.concat([df1, df2], axis=0, ignore_index=True)
result

   이름  점수
0  철수  85
1  영희  90
2  민수  78
3  지은  92

In [20]:
df3 = pd.DataFrame({
    "국어": [80, 90]
})
df4 = pd.DataFrame({
    "영어": [85, 95]
})
result2 = pd.concat([df3, df4], axis=1)
result2

   국어  영어
0  80  85
1  90  95

In [21]:
students = pd.DataFrame({
    "학번": [1, 2, 3],
    "이름": ["철수", "영희", "민수"]
})
scores = pd.DataFrame({
    "학번": [1, 2, 4],
    "점수": [85, 90, 70]
})
result3 = pd.merge(students, scores, on="학번")
result3

   학번  이름  점수
0   1  철수  85
1   2  영희  90

In [22]:
result4 = pd.merge(students, scores, on="학번", how="left")
result4

   학번  이름    점수
0   1  철수  85.0
1   2  영희  90.0
2   3  민수   NaN

In [24]:
pd.merge(students, scores, on="학번", how="right")

   학번   이름  점수
0   1   철수  85
1   2   영희  90
2   4  NaN  70

In [23]:
result5 = pd.merge(students, scores, on="학번", how="outer")
result5

   학번   이름    점수
0   1   철수  85.0
1   2   영희  90.0
2   3   민수   NaN
3   4  NaN  70.0