In [1]:
import pandas as pd
import numpy as np

In [2]:
student_data = {
    "이름": ["철수", "영희", "민수", "지은", "우진"],
    "국어": [80, np.nan, 70, 95, 60],
    "영어": [85, 90, np.nan, 88, 75],
    "수학": [np.nan, 95, 65, np.nan, 80]
}
df = pd.DataFrame(student_data)

1. 결측치가 있는 위치를 True/False로 확인해 보세요.

In [3]:
df.isnull()

      이름     국어     영어     수학
0  False  False  False   True
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4  False  False  False  False

2. 각 열(과목)별로 결측치가 몇 개씩 있는지 확인해 보세요.

In [4]:
df.isnull().sum()

이름    0
국어    1
영어    1
수학    2
dtype: int64

3. 결측치가 하나라도 있는 행을 모두 제거해 보세요. (원본은 유지)

In [5]:
df.dropna(how="any")

   이름    국어    영어    수학
4  우진  60.0  75.0  80.0

4. "수학" 열에 결측치가 있는 행만 제거해 보세요.

In [6]:
df.dropna(subset=["수학"])

   이름    국어    영어    수학
1  영희   NaN  90.0  95.0
2  민수  70.0   NaN  65.0
4  우진  60.0  75.0  80.0

5. 모든 결측치를 0으로 채워보세요.

In [7]:
df.fillna(0)

   이름    국어    영어    수학
0  철수  80.0  85.0   0.0
1  영희   0.0  90.0  95.0
2  민수  70.0   0.0  65.0
3  지은  95.0  88.0   0.0
4  우진  60.0  75.0  80.0

6. 결측치를 "국어"는 0으로, "영어"는 해당 열의 평균으로, "수학"은 해당 열의 평균으로 각각 다르게 채워보세요.

In [8]:
df.fillna({
    "국어": 0,
    "영어": df["영어"].mean(),
    "수학": df["수학"].mean()
})

   이름    국어    영어    수학
0  철수  80.0  85.0  80.0
1  영희   0.0  90.0  95.0
2  민수  70.0  84.5  65.0
3  지은  95.0  88.0  80.0
4  우진  60.0  75.0  80.0

7. "국어" 열의 결측치를 국어 평균값으로 채우고, 원본 df에 바로 반영해 보세요.

In [9]:
df.fillna(value = {"국어": df["국어"].mean()}, inplace = True)

   이름     국어    영어    수학
0  철수  80.00  85.0   NaN
1  영희  76.25  90.0  95.0
2  민수  70.00   NaN  65.0
3  지은  95.00  88.0   NaN
4  우진  60.00  75.0  80.0

8. 국어, 영어, 수학 점수를 모두 더한 "총점" 열을 새로 추가해 보세요. (6번에서 결측치를 처리한 데이터 기준으로 진행)

In [12]:
df = pd.DataFrame(student_data)
df.fillna(
    value = {
        "국어": 0,
        "영어": df["영어"].mean(),
        "수학": df["수학"].mean()
    },
    inplace = True
)
df["총점"] = df["국어"] + df["수학"] + df["영어"]
df

   이름    국어    영어    수학     총점
0  철수  80.0  85.0  80.0  245.0
1  영희   0.0  90.0  95.0  185.0
2  민수  70.0  84.5  65.0  219.5
3  지은  95.0  88.0  80.0  263.0
4  우진  60.0  75.0  80.0  215.0

9. "총점"을 3으로 나눈 "평균" 열을 추가하고, 평균이 80 이상이면 "합격", 아니면 "불합격"이 담긴 "결과" 열도 추가해 보세요.

In [13]:
df["평균"] = df["총점"] / 3
df["결과"] = df["평균"].apply(lambda avg: "합격" if avg >= 80 else "불합격")
df

   이름    국어    영어    수학     총점         평균   결과
0  철수  80.0  85.0  80.0  245.0  81.666667   합격
1  영희   0.0  90.0  95.0  185.0  61.666667  불합격
2  민수  70.0  84.5  65.0  219.5  73.166667  불합격
3  지은  95.0  88.0  80.0  263.0  87.666667   합격
4  우진  60.0  75.0  80.0  215.0  71.666667  불합격

10. "결과" 열을 삭제해 보세요. (원본 자체가 바로 바뀌도록)

In [14]:
df.drop(columns = ["결과"], inplace = True)
df

   이름    국어    영어    수학     총점         평균
0  철수  80.0  85.0  80.0  245.0  81.666667
1  영희   0.0  90.0  95.0  185.0  61.666667
2  민수  70.0  84.5  65.0  219.5  73.166667
3  지은  95.0  88.0  80.0  263.0  87.666667
4  우진  60.0  75.0  80.0  215.0  71.666667

11. "국어" 열 이름을 "한국어"로, "영어" 열 이름을 "English"로 바꿔보세요.

In [17]:
df.rename(
    columns = {
        "국어": "한국어",
        "영어": "English"
    }, 
    inplace = True
)
df

   이름   한국어  English    수학     총점         평균
0  철수  80.0     85.0  80.0  245.0  81.666667
1  영희   0.0     90.0  95.0  185.0  61.666667
2  민수  70.0     84.5  65.0  219.5  73.166667
3  지은  95.0     88.0  80.0  263.0  87.666667
4  우진  60.0     75.0  80.0  215.0  71.666667