In [2]:
import pandas as pd

In [5]:
data = {
    "이름": [" 철수 ", "영희", " 민수"],
    "이메일": ["cheol@test.com", "young@Test.com", "min@test.COM"]
}
df = pd.DataFrame(data)
df

     이름             이메일
0   철수   cheol@test.com
1    영희  young@Test.com
2    민수    min@test.COM

In [6]:
df["이름"] = df["이름"].str.strip()
df

   이름             이메일
0  철수  cheol@test.com
1  영희  young@Test.com
2  민수    min@test.COM

In [7]:
df["이메일"] = df["이메일"].str.lower()
df

   이름             이메일
0  철수  cheol@test.com
1  영희  young@test.com
2  민수    min@test.com

In [9]:
df["이메일"].str.contains("test")

0    True
1    True
2    True
Name: 이메일, dtype: bool

In [10]:
df["이메일2"] = df["이메일"].str.replace("test.com", "example.com")
df["이메일2"]

0    cheol@example.com
1    young@example.com
2      min@example.com
Name: 이메일2, dtype: str

In [11]:
df["이름"].str.len()

0    2
1    2
2    2
Name: 이름, dtype: int64

In [12]:
df["이메일"].str[:4]

0    cheo
1    youn
2    min@
Name: 이메일, dtype: str

In [13]:
data = {
    "이름": ["철수", "영희", "민수"],
    "국어": [80, 90, 70],
    "영어": [85, 95, 75]
}
df = pd.DataFrame(data)
df

   이름  국어  영어
0  철수  80  85
1  영희  90  95
2  민수  70  75

In [14]:
def to_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

In [15]:
df["국어등급"] = df["국어"].apply(to_grade)
df

   이름  국어  영어 국어등급
0  철수  80  85    B
1  영희  90  95    A
2  민수  70  75    C

In [16]:
df["평균"] = df.apply(lambda row: (row["국어"] + row["영어"]) / 2, axis = 1)
df

   이름  국어  영어 국어등급    평균
0  철수  80  85    B  82.5
1  영희  90  95    A  92.5
2  민수  70  75    C  72.5

In [17]:
import pandas as pd
import numpy as np

In [19]:
data = {
    "이름": ["철수", "영희", "민수", "지은", "우진", "하늘"],
    "부서": ["영업", "영업", "개발", "개발", "인사", "개발"],
    "연봉": [3500, 4000, 5000, np.nan, 3800, 5200],
    "나이": [28, 32, 27, 30, 26, 35]
}
df = pd.DataFrame(data)
print(df)
print(df.info())
print(df.describe())

   이름  부서      연봉  나이
0  철수  영업  3500.0  28
1  영희  영업  4000.0  32
2  민수  개발  5000.0  27
3  지은  개발     NaN  30
4  우진  인사  3800.0  26
5  하늘  개발  5200.0  35
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      6 non-null      str
 1   부서      6 non-null      str
 2   연봉      5 non-null      float64
 3   나이      6 non-null      int64
dtypes: float64(1), int64(1), str(2)
memory usage: 324.0 bytes
None
                연봉         나이
count     5.000000   6.000000
mean   4300.000000  29.666667
std     754.983444   3.386247
min    3500.000000  26.000000
25%    3800.000000  27.250000
50%    4000.000000  29.000000
75%    5000.000000  31.500000
max    5200.000000  35.000000

In [24]:
df["연봉"] = df.groupby("부서")["연봉"].transform(lambda x: x.fillna(x.mean()))
df

   이름  부서      연봉  나이
0  철수  영업  3500.0  28
1  영희  영업  4000.0  32
2  민수  개발  5000.0  27
3  지은  개발  5100.0  30
4  우진  인사  3800.0  26
5  하늘  개발  5200.0  35

In [25]:
def salary_grade(salary):
    if salary >= 5000:
        return "고연봉"
    elif salary >= 4000:
        return "중연봉"
    else:
        return "저연봉"

In [26]:
df["연봉등급"] = df["연봉"].apply(salary_grade)
df

   이름  부서      연봉  나이 연봉등급
0  철수  영업  3500.0  28  저연봉
1  영희  영업  4000.0  32  중연봉
2  민수  개발  5000.0  27  고연봉
3  지은  개발  5100.0  30  고연봉
4  우진  인사  3800.0  26  저연봉
5  하늘  개발  5200.0  35  고연봉

In [28]:
summary = df.groupby("부서").agg(평균연봉=("연봉", "mean"), 인원수=("이름", "count"))
summary

      평균연봉  인원수
부서
개발  5100.0    3
영업  3750.0    2
인사  3800.0    1

In [30]:
top3 = df.sort_values(by="연봉", ascending=False).head(3)
top3

   이름  부서      연봉  나이 연봉등급
5  하늘  개발  5200.0  35  고연봉
3  지은  개발  5100.0  30  고연봉
2  민수  개발  5000.0  27  고연봉

In [31]:
df.to_csv("employee_result.csv", index=False, encoding="utf-8-sig")