In [1]:
import pandas as pd

sales_data = {
    "지점": ["강남", "강남", "홍대", "홍대", "잠실", "잠실"],
    "담당자": ["김민수", "이지은", "박철수", "최영희", "정우진", "한소희"],
    "매출": [4200, 3800, 5100, 4900, 3600, 4700],
    "고객수": [120, 95, 150, 140, 88, 130]
}

# 지점 정보 (merge 실습용, '부산'은 sales_data에 없는 지점)
branch_info = {
    "지점": ["강남", "홍대", "잠실", "부산"],
    "지역": ["서울 강남권", "서울 서북권", "서울 동남권", "부산"],
    "오픈연도": [2015, 2018, 2020, 2022]
}

# 신규 지점 실적 (concat 실습용, sales_data와 열 구성이 동일)
new_sales_data = {
    "지점": ["신촌", "신촌"],
    "담당자": ["오세훈", "윤아름"],
    "매출": [4400, 3900],
    "고객수": [110, 100]
}

sales_df = pd.DataFrame(sales_data)
branch_df = pd.DataFrame(branch_info)
new_sales_df = pd.DataFrame(new_sales_data)

### 정렬 (sort)
1. 매출을 기준으로 오름차순 정렬해 보세요.
2. 매출을 기준으로 내림차순 정렬해 보세요.
3. "지점"을 기준으로 오름차순, 동점(같은 지점)일 경우 "매출"을 내림차순으로 정렬해 보세요.
4. 3번 정렬 결과의 인덱스를 0부터 다시 매겨보세요. (기존 인덱스는 버리기)
5. 데이터프레임의 행 인덱스를 기준으로 정렬해 보세요.
6. 데이터프레임의 열 이름을 기준으로 정렬해 보세요.

In [2]:
# 1
sales_df.sort_values("매출")

   지점  담당자    매출  고객수
4  잠실  정우진  3600   88
1  강남  이지은  3800   95
0  강남  김민수  4200  120
5  잠실  한소희  4700  130
3  홍대  최영희  4900  140
2  홍대  박철수  5100  150

In [4]:
# 2
sales_df.sort_values("매출", ascending=False)

   지점  담당자    매출  고객수
2  홍대  박철수  5100  150
3  홍대  최영희  4900  140
5  잠실  한소희  4700  130
0  강남  김민수  4200  120
1  강남  이지은  3800   95
4  잠실  정우진  3600   88

In [7]:
# 3
sorted = sales_df.sort_values(["지점", "매출"], ascending=[True, False])
sorted

   지점  담당자    매출  고객수
0  강남  김민수  4200  120
1  강남  이지은  3800   95
5  잠실  한소희  4700  130
4  잠실  정우진  3600   88
2  홍대  박철수  5100  150
3  홍대  최영희  4900  140

In [10]:
# 4
sorted.reset_index(drop=True, inplace=True)
sorted

   지점  담당자    매출  고객수
0  강남  김민수  4200  120
1  강남  이지은  3800   95
2  잠실  한소희  4700  130
3  잠실  정우진  3600   88
4  홍대  박철수  5100  150
5  홍대  최영희  4900  140

In [12]:
# 5
sales_df.sort_index()

   지점  담당자    매출  고객수
0  강남  김민수  4200  120
1  강남  이지은  3800   95
2  홍대  박철수  5100  150
3  홍대  최영희  4900  140
4  잠실  정우진  3600   88
5  잠실  한소희  4700  130

In [13]:
# 6
sales_df.sort_index(axis=1)

   고객수  담당자    매출  지점
0  120  김민수  4200  강남
1   95  이지은  3800  강남
2  150  박철수  5100  홍대
3  140  최영희  4900  홍대
4   88  정우진  3600  잠실
5  130  한소희  4700  잠실

### 그룹화 (groupby)
7. 지점별 평균 매출을 구해보세요.
8. 지점별 고객수 합계를 구해보세요.
9. 지점별로 매출의 평균, 합계, 개수를 한 번에 확인해 보세요.
10. 지점별로 "매출"은 평균, "고객수"는 최댓값을 각각 다르게 집계해 보세요.
11. 지점별 평균 매출을 구한 뒤, 매출이 높은 순서로 정렬해 보세요.

In [14]:
# 7
sales_df.groupby("지점")["매출"].mean()

지점
강남    4000.0
잠실    4150.0
홍대    5000.0
Name: 매출, dtype: float64

In [15]:
# 8
sales_df.groupby("지점")["고객수"].sum()

지점
강남    215
잠실    218
홍대    290
Name: 고객수, dtype: int64

In [16]:
# 9
sales_df.groupby("지점")["매출"].agg(["mean", "sum", "count"])

      mean    sum  count
지점
강남  4000.0   8000      2
잠실  4150.0   8300      2
홍대  5000.0  10000      2

In [18]:
# 10
sales_df.groupby("지점").agg(평균매출=("매출", "mean"), 최대고객수=("고객수", "max"))

      평균매출  최대고객수
지점
강남  4000.0    120
잠실  4150.0    130
홍대  5000.0    150

In [22]:
# 11
sales_df.groupby("지점")["매출"].mean().sort_values(ascending=False)

지점
홍대    5000.0
잠실    4150.0
강남    4000.0
Name: 매출, dtype: float64

### 병합 (merge)
12. sales_df와 branch_df를 "지점" 열을 기준으로 병합하되, 양쪽에 모두 존재하는 지점만 남겨보세요. (inner join)
13. sales_df와 branch_df를 "지점" 기준으로 병합하되, 어느 한쪽에만 있는 지점(부산)까지 모두 포함하고, 값이 없는 칸이 어떻게 채워지는지 확인해 보세요. (outer join)

In [23]:
# 12
pd.merge(sales_df, branch_df, on="지점", how="inner")

   지점  담당자    매출  고객수      지역  오픈연도
0  강남  김민수  4200  120  서울 강남권  2015
1  강남  이지은  3800   95  서울 강남권  2015
2  홍대  박철수  5100  150  서울 서북권  2018
3  홍대  최영희  4900  140  서울 서북권  2018
4  잠실  정우진  3600   88  서울 동남권  2020
5  잠실  한소희  4700  130  서울 동남권  2020

In [24]:
# 13
pd.merge(sales_df, branch_df, on="지점", how="outer")

   지점  담당자      매출    고객수      지역  오픈연도
0  강남  김민수  4200.0  120.0  서울 강남권  2015
1  강남  이지은  3800.0   95.0  서울 강남권  2015
2  부산  NaN     NaN    NaN      부산  2022
3  잠실  정우진  3600.0   88.0  서울 동남권  2020
4  잠실  한소희  4700.0  130.0  서울 동남권  2020
5  홍대  박철수  5100.0  150.0  서울 서북권  2018
6  홍대  최영희  4900.0  140.0  서울 서북권  2018

### 연결 (concat)
14. sales_df와 new_sales_df를 위아래로 이어 붙이고, 인덱스를 0부터 다시 매겨보세요.

In [28]:
# 14
pd.concat([sales_df, new_sales_df], axis=0).reset_index(drop=True)

   지점  담당자    매출  고객수
0  강남  김민수  4200  120
1  강남  이지은  3800   95
2  홍대  박철수  5100  150
3  홍대  최영희  4900  140
4  잠실  정우진  3600   88
5  잠실  한소희  4700  130
6  신촌  오세훈  4400  110
7  신촌  윤아름  3900  100